import * as yup from 'yup';
import { SlEnvolope } from 'react-icons/sl';
import { FaRegUserCircle } from 'react-icons/fa';
import { TbTriangleSquareCircle } from 'react-icons/tb';
import { AiOutlineMobile } from 'react-icons/ai';
export const loginForm = [
  {
    name: 'email',
    label: 'Email',
    type: 'text',
    placeholder: 'info@example.com',
    Icon: SlEnvolope,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
];
export const signUpForm = [
  {
    name: 'username',
    label: 'User Name',
    type: 'text',
    placeholder: 'robertjonson',
    Icon: FaRegUserCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },

  // {
  //   name: 'password',
  //   label: 'Password',
  //   type: 'password',
  //   placeholder: 'Password',
  //   isEye: true,
  //   valtype: 'string',
  //   methods: [{ type: 'required', params: ['This is a required field'] }],
  // },
  {
    name: 'email',
    label: 'Email',
    type: 'text',
    placeholder: 'info@example.com',
    Icon: SlEnvolope,
    valtype: 'string',
    methods: [
      { type: 'email', params: ['Please enter valid email'] },
      { type: 'required', params: ['This is a required field'] },
    ],
  },
  {
    name: 'phone',
    label: 'Phone',
    type: 'text',
    placeholder: '9876543210',
    Icon: SlEnvolope,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'agree',
    label: 'Here, I will agree company terms & conditions.',
    type: 'checkbox',
    placeholder: '',
    valtype: 'bool',
    methods: [{ type: 'oneOf', params: [[true], 'Please accept terms & conditions'] }],
  },
];
export const signUpCandidate = [
  {
    name: 'firstname',
    label: 'First Name',
    type: 'text',
    placeholder: 'Mr.Robert',
    Icon: FaRegUserCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'lastname',
    label: 'Last Name',
    type: 'text',
    placeholder: 'Jonson',
    Icon: FaRegUserCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'username',
    label: 'User Name',
    type: 'text',
    placeholder: 'robertjonson',
    Icon: FaRegUserCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'email',
    label: 'Email',
    type: 'text',
    placeholder: 'info@example.com',
    Icon: SlEnvolope,
    valtype: 'string',
    methods: [
      { type: 'email', params: ['Please enter valid email'] },
      { type: 'required', params: ['This is a required field'] },
    ],
  },
  {
    name: 'password',
    label: 'Password',
    type: 'password',
    placeholder: 'Password',
    isEye: true,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'confirmpassword',
    label: 'Confirm Password',
    type: 'password',
    placeholder: 'Password',
    isEye: true,
    valtype: 'string',
    methods: [{ type: 'oneOf', params: [[yup.ref('password')]] }],
  },
  {
    name: 'agree',
    label: 'Here, I will agree company terms & conditions.',
    type: 'checkbox',
    placeholder: '',
    valtype: 'bool',
    methods: [{ type: 'oneOf', params: [[true], 'Please accept terms & conditions'] }],
  },
];

export const signUpCompany = [
  {
    name: 'firstname',
    label: 'First Name',
    type: 'text',
    placeholder: 'Mr.Robert',
    Icon: FaRegUserCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'lastname',
    label: 'Last Name',
    type: 'text',
    placeholder: 'Jonson',
    Icon: FaRegUserCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'username',
    label: 'User Name',
    type: 'text',
    placeholder: 'robertjonson',
    Icon: FaRegUserCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'email',
    label: 'Email',
    type: 'text',
    placeholder: 'info@example.com',
    Icon: SlEnvolope,
    valtype: 'string',
    methods: [
      { type: 'email', params: ['Please enter valid email'] },
      { type: 'required', params: ['This is a required field'] },
    ],
  },
  {
    name: 'companyname',
    label: 'Company Name',
    type: 'text',
    placeholder: 'Mr.Robert',
    Icon: TbTriangleSquareCircle,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'companytype',
    label: 'Company Type',
    type: 'select',
    placeholder: 'Select',
    Icon: TbTriangleSquareCircle,
    options: [
      { name: 'Digital Agency', value: '0' },
      { name: 'Digital Marketing Agency', value: '1' },
      { name: 'Software Company', value: '2' },
    ],
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'password',
    label: 'Password',
    type: 'password',
    placeholder: 'Password',
    isEye: true,
    valtype: 'string',
    methods: [{ type: 'required', params: ['This is a required field'] }],
  },
  {
    name: 'confirmpassword',
    label: 'Confirm Password',
    type: 'password',
    placeholder: 'Password',
    isEye: true,
    valtype: 'string',
    methods: [{ type: 'oneOf', params: [[yup.ref('password')]] }],
  },
  {
    name: 'agree',
    label: 'Here, I will agree company terms & conditions.',
    type: 'checkbox',
    placeholder: '',
    valtype: 'bool',
    methods: [{ type: 'oneOf', params: [[true], 'Please accept terms & conditions'] }],
  },
];
