import Head from 'next/head';
import Layout from '@components/laylout';
import Banner from '@views/home/banner';
import styles from '@styles/home.module.scss';
import About from '@views/home/about';
import UseCase from '@views/home/use-case';
import GetStart from '@views/home/get-started';
import { useSelector } from 'react-redux';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout isFooter={true}>
        <Banner styles={styles} />
        <About styles={styles} />
        <UseCase styles={styles} />
        <GetStart styles={styles} />
      </Layout>
    </>
  );
}
