import Layout from '@components/laylout';
import styles from '@styles/documents.module.scss';
import Head from 'next/head';

import AiChatBox from '@components/ai-chat-box';
import PdfViewer from '@components/pdf-viewer';

export default function Chat() {
  return (
    <>
      <Head>
        <title>chat with your pdf docs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout headerClass="nav-bg" login_nav={true} bodyOverflow={true}>
        <div className={`${styles.container} d-flex overflow-auto`}>
          <div className="flex-1 overflow-auto">
            <PdfViewer file="/images/PDF.pdf" />
          </div>
          <AiChatBox />
        </div>
      </Layout>
    </>
  );
}
